-- =============================================================================
-- SEED 033: Catálogo masivo de ferretería (~250 productos reales argentinos)
-- Actualiza business_type_templates.products para 'ferreteria'
-- Marcas nacionales reales: Lusqtoff, Bahco, Hamilton, Stanley, Bosch, Makita,
--   FV, Tigre, Alba, Sinteplast, Poxipol, La Gotita, Acindar, Loma Negra, etc.
-- =============================================================================

UPDATE business_type_templates
SET products = '[
  {"name": "Cemento Portland Loma Negra 50kg", "category_slug": "cementos-cales", "brand": "Loma Negra", "price_reference": 9500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cemento Portland Avellaneda 50kg", "category_slug": "cementos-cales", "brand": "Avellaneda", "price_reference": 9200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cal hidráulica Loma Negra 25kg", "category_slug": "cementos-cales", "brand": "Loma Negra", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cal hidratada Cacique 25kg", "category_slug": "cementos-cales", "brand": "Cacique", "price_reference": 3200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pegamento para cerámicos Weber 30kg", "category_slug": "cementos-cales", "brand": "Weber", "price_reference": 7500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pastina Weber color blanco 2kg", "category_slug": "cementos-cales", "brand": "Weber", "price_reference": 2800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Ladrillo hueco 8x18x33", "category_slug": "ladrillos-bloques", "brand": null, "price_reference": 120, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ladrillo hueco 12x18x33", "category_slug": "ladrillos-bloques", "brand": null, "price_reference": 180, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ladrillo hueco 18x18x33", "category_slug": "ladrillos-bloques", "brand": null, "price_reference": 250, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bloque de hormigón 13x19x39", "category_slug": "ladrillos-bloques", "brand": null, "price_reference": 280, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ladrillo visto 6x12x25", "category_slug": "ladrillos-bloques", "brand": null, "price_reference": 90, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Hierro ø6mm x 12m Acindar", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 5500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hierro ø8mm x 12m Acindar", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 8500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hierro ø10mm x 12m Acindar", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 13000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hierro ø12mm x 12m Acindar", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 18500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Malla sima 15x15 ø4.2mm 2x3m", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 22000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Alambre negro recocido 16BWG x1kg", "category_slug": "hierros-acero", "brand": "Acindar", "price_reference": 2500, "unit": "kg", "sku_prefix": "FERRET"},

  {"name": "Membrana asfáltica 4mm x 10m² Megaflex", "category_slug": "membranas-aislantes", "brand": "Megaflex", "price_reference": 32000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Membrana asfáltica 4mm x 10m² Sika", "category_slug": "membranas-aislantes", "brand": "Sika", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Membrana líquida Sika 20L", "category_slug": "membranas-aislantes", "brand": "Sika", "price_reference": 42000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Espuma de poliuretano Fischbein 750ml", "category_slug": "membranas-aislantes", "brand": "Fischbein", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Telgopor EPS 25mm 1x1m", "category_slug": "membranas-aislantes", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Arena fina bolsa 25kg", "category_slug": "arenas-aridos", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Arena gruesa bolsa 25kg", "category_slug": "arenas-aridos", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Piedra partida bolsa 25kg", "category_slug": "arenas-aridos", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cascote fino bolsa 25kg", "category_slug": "arenas-aridos", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Martillo carpintero Stanley 500g", "category_slug": "martillos-mazas", "brand": "Stanley", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Martillo carpintero Bahco 570g", "category_slug": "martillos-mazas", "brand": "Bahco", "price_reference": 15000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Martillo de goma 500g", "category_slug": "martillos-mazas", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Maza 1kg con mango madera", "category_slug": "martillos-mazas", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Martillo uña Hamilton 20oz", "category_slug": "martillos-mazas", "brand": "Hamilton", "price_reference": 8500, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Destornillador Phillips PH2 Stanley", "category_slug": "destornilladores", "brand": "Stanley", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Destornillador plano 6mm Stanley", "category_slug": "destornilladores", "brand": "Stanley", "price_reference": 3200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Juego destornilladores 6 piezas Bahco", "category_slug": "destornilladores", "brand": "Bahco", "price_reference": 18000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Destornillador buscapolo", "category_slug": "destornilladores", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Juego destornilladores 10 piezas Hamilton", "category_slug": "destornilladores", "brand": "Hamilton", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Puntas Phillips PH2 x10 unidades", "category_slug": "destornilladores", "brand": "Bosch", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Llave francesa 10\" Stanley", "category_slug": "llaves-pinzas", "brand": "Stanley", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llave francesa 12\" Bahco", "category_slug": "llaves-pinzas", "brand": "Bahco", "price_reference": 22000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pinza universal 8\" Bahco", "category_slug": "llaves-pinzas", "brand": "Bahco", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pinza de presión 10\" Hamilton", "category_slug": "llaves-pinzas", "brand": "Hamilton", "price_reference": 6500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Alicate de corte diagonal 6\" Bahco", "category_slug": "llaves-pinzas", "brand": "Bahco", "price_reference": 9000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Juego llaves combinadas 8-19mm Hamilton", "category_slug": "llaves-pinzas", "brand": "Hamilton", "price_reference": 18000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Juego llaves Allen 1.5-10mm", "category_slug": "llaves-pinzas", "brand": "Stanley", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llave tubo 10\" Hamilton", "category_slug": "llaves-pinzas", "brand": "Hamilton", "price_reference": 7000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pinza pico largo 8\" Bahco", "category_slug": "llaves-pinzas", "brand": "Bahco", "price_reference": 10000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Serrucho 20\" Bahco", "category_slug": "sierras-serruchos", "brand": "Bahco", "price_reference": 15000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sierra para metales 12\"", "category_slug": "sierras-serruchos", "brand": "Stanley", "price_reference": 5500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hoja de sierra para metales x2", "category_slug": "sierras-serruchos", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Serrucho para poda 14\"", "category_slug": "sierras-serruchos", "brand": "Bahco", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Cinta métrica 5m Stanley", "category_slug": "medicion-trazado", "brand": "Stanley", "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta métrica 8m Stanley", "category_slug": "medicion-trazado", "brand": "Stanley", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Nivel de burbuja 40cm Stanley", "category_slug": "medicion-trazado", "brand": "Stanley", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Nivel de burbuja 60cm Bahco", "category_slug": "medicion-trazado", "brand": "Bahco", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Escuadra carpintero 30cm", "category_slug": "medicion-trazado", "brand": "Stanley", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Plomada de albañil 500g", "category_slug": "medicion-trazado", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Lápiz de carpintero x3", "category_slug": "medicion-trazado", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Taladro percutor Bosch GSB 550 550W", "category_slug": "taladros-percutores", "brand": "Bosch", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Taladro percutor Bosch GSB 13RE 650W", "category_slug": "taladros-percutores", "brand": "Bosch", "price_reference": 48000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Taladro percutor Lusqtoff TP-713 13mm 850W", "category_slug": "taladros-percutores", "brand": "Lusqtoff", "price_reference": 28000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Taladro atornillador inalámbrico Makita 12V", "category_slug": "taladros-percutores", "brand": "Makita", "price_reference": 65000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Taladro percutor Black+Decker 550W", "category_slug": "taladros-percutores", "brand": "Black+Decker", "price_reference": 32000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Rotomartillo SDS Plus Bosch GBH 220 720W", "category_slug": "taladros-percutores", "brand": "Bosch", "price_reference": 85000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Taladro de banco 13mm Lusqtoff", "category_slug": "taladros-percutores", "brand": "Lusqtoff", "price_reference": 95000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Amoladora angular 4½\" Bosch GWS 700 700W", "category_slug": "amoladoras", "brand": "Bosch", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Amoladora angular 4½\" Bosch GWS 850 850W", "category_slug": "amoladoras", "brand": "Bosch", "price_reference": 42000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Amoladora angular 4½\" Lusqtoff 850W", "category_slug": "amoladoras", "brand": "Lusqtoff", "price_reference": 25000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Amoladora angular 7\" DeWalt 2200W", "category_slug": "amoladoras", "brand": "DeWalt", "price_reference": 95000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Amoladora angular 4½\" Hamilton 750W", "category_slug": "amoladoras", "brand": "Hamilton", "price_reference": 22000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Sierra caladora Bosch GST 650 450W", "category_slug": "sierras-electricas", "brand": "Bosch", "price_reference": 38000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sierra caladora Black+Decker 550W", "category_slug": "sierras-electricas", "brand": "Black+Decker", "price_reference": 32000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sierra circular Bosch GKS 7000 1100W", "category_slug": "sierras-electricas", "brand": "Bosch", "price_reference": 65000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sierra circular Lusqtoff 7¼\" 1200W", "category_slug": "sierras-electricas", "brand": "Lusqtoff", "price_reference": 45000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ingletadora 10\" Lusqtoff", "category_slug": "sierras-electricas", "brand": "Lusqtoff", "price_reference": 120000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Atornillador inalámbrico Makita 12V", "category_slug": "atornilladores-electricos", "brand": "Makita", "price_reference": 55000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Atornillador inalámbrico Bosch GSR 120-LI 12V", "category_slug": "atornilladores-electricos", "brand": "Bosch", "price_reference": 48000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Atornillador inalámbrico Black+Decker 12V", "category_slug": "atornilladores-electricos", "brand": "Black+Decker", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Atornillador de impacto inalámbrico Lusqtoff 20V", "category_slug": "atornilladores-electricos", "brand": "Lusqtoff", "price_reference": 42000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Juego mechas acero rápido 1-10mm x13 Bosch", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Mecha para concreto 6mm Bosch", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Mecha para concreto 8mm Bosch", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Mecha para concreto 10mm Bosch", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Disco de corte 4½\" x25 unidades", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Disco de desbaste 4½\"", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Mecha para madera paleta 20mm", "category_slug": "accesorios-mechas", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Mecha copa bi-metal 32mm", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hoja de sierra caladora madera x5", "category_slug": "accesorios-mechas", "brand": "Bosch", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Lija al agua 220 x10 hojas", "category_slug": "accesorios-mechas", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Tornillo para madera 4x40mm x100", "category_slug": "tornillos", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tornillo para madera 4x50mm x100", "category_slug": "tornillos", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tornillo para madera 5x60mm x100", "category_slug": "tornillos", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tornillo autoperforante 8x1\" x100", "category_slug": "tornillos", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tornillo autoperforante 10x1½\" x100", "category_slug": "tornillos", "brand": null, "price_reference": 2200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tornillo para durlock 6x1\" x100", "category_slug": "tornillos", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tirafondo hexagonal 8x60mm x50", "category_slug": "tornillos", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bulón cabeza hexagonal 8x50mm x10", "category_slug": "tornillos", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Clavo 1\" punta París x1kg", "category_slug": "clavos", "brand": null, "price_reference": 2000, "unit": "kg", "sku_prefix": "FERRET"},
  {"name": "Clavo 2\" punta París x1kg", "category_slug": "clavos", "brand": null, "price_reference": 2000, "unit": "kg", "sku_prefix": "FERRET"},
  {"name": "Clavo 3\" punta París x1kg", "category_slug": "clavos", "brand": null, "price_reference": 2200, "unit": "kg", "sku_prefix": "FERRET"},
  {"name": "Clavo para chapa x1kg", "category_slug": "clavos", "brand": null, "price_reference": 3000, "unit": "kg", "sku_prefix": "FERRET"},
  {"name": "Grampas para cercas x1kg", "category_slug": "clavos", "brand": null, "price_reference": 3500, "unit": "kg", "sku_prefix": "FERRET"},

  {"name": "Tarugo nylon 6mm x100", "category_slug": "tarugos-bulones", "brand": "Fischer", "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tarugo nylon 8mm x100", "category_slug": "tarugos-bulones", "brand": "Fischer", "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tarugo nylon 10mm x50", "category_slug": "tarugos-bulones", "brand": "Fischer", "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tarugo mariposa para durlock 8mm x10", "category_slug": "tarugos-bulones", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Arandela plana ¼\" x100", "category_slug": "tarugos-bulones", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tuerca hexagonal 8mm x50", "category_slug": "tarugos-bulones", "brand": null, "price_reference": 900, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Remache pop 4x10mm x100", "category_slug": "tarugos-bulones", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Caño PVC 50mm x 4m Tigre", "category_slug": "canos-pvc", "brand": "Tigre", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caño PVC 63mm x 4m Tigre", "category_slug": "canos-pvc", "brand": "Tigre", "price_reference": 5500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caño PVC 110mm x 4m Tigre", "category_slug": "canos-pvc", "brand": "Tigre", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caño agua fría 1/2\" x 4m", "category_slug": "canos-pvc", "brand": "Tigre", "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caño agua caliente 1/2\" x 4m (termofusión)", "category_slug": "canos-pvc", "brand": "Tigre", "price_reference": 3200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caño corrugado 1\" x 25m", "category_slug": "canos-pvc", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Codo PVC 50mm a 90°", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 350, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Codo PVC 110mm a 90°", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 600, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Te PVC 110mm", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cupla PVC 110mm", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 400, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Reducción PVC 110 a 63mm", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta teflón 1/2\" x 10m", "category_slug": "conexiones-accesorios-plom", "brand": null, "price_reference": 300, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Adhesivo para PVC 100g", "category_slug": "conexiones-accesorios-plom", "brand": "Tigre", "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sopapa para inodoro", "category_slug": "conexiones-accesorios-plom", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Destapacañerías manual tipo ventosa", "category_slug": "conexiones-accesorios-plom", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Grifería monocomando cocina FV Libby", "category_slug": "griferias-ferret", "brand": "FV", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Grifería monocomando baño FV Grifon", "category_slug": "griferias-ferret", "brand": "FV", "price_reference": 28000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Canilla doble cierre bronce ½\"", "category_slug": "griferias-ferret", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ducha teléfono con flexible", "category_slug": "griferias-ferret", "brand": "FV", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llave de paso ½\" bronce", "category_slug": "griferias-ferret", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Válvula esférica ½\" bronce", "category_slug": "griferias-ferret", "brand": null, "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Tanque de agua Tigre 500L", "category_slug": "tanques-flotantes", "brand": "Tigre", "price_reference": 55000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tanque de agua Tigre 1000L", "category_slug": "tanques-flotantes", "brand": "Tigre", "price_reference": 85000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Flotante completo para tanque", "category_slug": "tanques-flotantes", "brand": "FV", "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Válvula flotante bronce ¾\"", "category_slug": "tanques-flotantes", "brand": "FV", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Cable unipolar 1.5mm² x100m", "category_slug": "cables-ferret", "brand": "IMSA", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cable unipolar 2.5mm² x100m", "category_slug": "cables-ferret", "brand": "IMSA", "price_reference": 18000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cable unipolar 4mm² x100m", "category_slug": "cables-ferret", "brand": "IMSA", "price_reference": 28000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cable bajo plomo 2x1.5mm² x100m", "category_slug": "cables-ferret", "brand": null, "price_reference": 25000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cable taller 3x1.5mm² x1m", "category_slug": "cables-ferret", "brand": null, "price_reference": 600, "unit": "metro", "sku_prefix": "FERRET"},
  {"name": "Prolongador eléctrico 10m", "category_slug": "cables-ferret", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Llave térmica 16A Schneider", "category_slug": "llaves-termicas", "brand": "Schneider", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llave térmica 20A Schneider", "category_slug": "llaves-termicas", "brand": "Schneider", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llave térmica 32A Schneider", "category_slug": "llaves-termicas", "brand": "Schneider", "price_reference": 6500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Disyuntor diferencial 2x25A 30mA Schneider", "category_slug": "llaves-termicas", "brand": "Schneider", "price_reference": 18000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tablero embutir 6 módulos", "category_slug": "llaves-termicas", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tablero embutir 12 módulos", "category_slug": "llaves-termicas", "brand": null, "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Tomacorriente doble 10A blanco", "category_slug": "tomas-interruptores-ferret", "brand": "Jeluz", "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Interruptor de luz simple blanco", "category_slug": "tomas-interruptores-ferret", "brand": "Jeluz", "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Interruptor doble blanco", "category_slug": "tomas-interruptores-ferret", "brand": "Jeluz", "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Toma 20A para aire acondicionado", "category_slug": "tomas-interruptores-ferret", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caja rectangular embutir PVC", "category_slug": "tomas-interruptores-ferret", "brand": null, "price_reference": 250, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caja octogonal embutir PVC", "category_slug": "tomas-interruptores-ferret", "brand": null, "price_reference": 200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ficha macho 10A", "category_slug": "tomas-interruptores-ferret", "brand": null, "price_reference": 400, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Ficha hembra 10A", "category_slug": "tomas-interruptores-ferret", "brand": null, "price_reference": 500, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Lámpara LED 9W E27 fría", "category_slug": "iluminacion-ferret", "brand": "Philips", "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Lámpara LED 12W E27 cálida", "category_slug": "iluminacion-ferret", "brand": "Philips", "price_reference": 1800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tubo LED 18W 120cm frío", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Reflector LED 30W exterior", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Reflector LED 50W exterior", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Dicroica LED GU10 7W", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Plafón LED 18W embutir redondo", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tira LED 5050 5m blanca fría", "category_slug": "iluminacion-ferret", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Pintura látex interior Alba 20L", "category_slug": "latex-ferret", "brand": "Alba", "price_reference": 55000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pintura látex interior Alba 4L", "category_slug": "latex-ferret", "brand": "Alba", "price_reference": 15000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pintura látex interior Alba 1L", "category_slug": "latex-ferret", "brand": "Alba", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pintura látex exterior Sinteplast 20L", "category_slug": "latex-ferret", "brand": "Sinteplast", "price_reference": 65000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pintura látex exterior Sinteplast 4L", "category_slug": "latex-ferret", "brand": "Sinteplast", "price_reference": 18000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pintura látex interior Colorín 20L", "category_slug": "latex-ferret", "brand": "Colorín", "price_reference": 48000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Enduido plástico Alba 4L", "category_slug": "latex-ferret", "brand": "Alba", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Fijador sellador al agua 4L", "category_slug": "latex-ferret", "brand": "Alba", "price_reference": 7000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Esmalte sintético brillante 1L Alba", "category_slug": "esmaltes-ferret", "brand": "Alba", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Esmalte sintético brillante 4L Alba", "category_slug": "esmaltes-ferret", "brand": "Alba", "price_reference": 25000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Convertidor de óxido 1L", "category_slug": "esmaltes-ferret", "brand": "Sinteplast", "price_reference": 5500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Esmalte al agua 1L Sinteplast", "category_slug": "esmaltes-ferret", "brand": "Sinteplast", "price_reference": 7500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Barniz marino 1L Cetol", "category_slug": "esmaltes-ferret", "brand": "Cetol", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Protector para maderas Cetol 1L", "category_slug": "esmaltes-ferret", "brand": "Cetol", "price_reference": 14000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Diluyente para esmalte sintético 1L", "category_slug": "esmaltes-ferret", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Aguarrás mineral 1L", "category_slug": "esmaltes-ferret", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Rodillo lana antigota 23cm", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Rodillo espuma 10cm mini", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pincel 2\" cerda natural", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pincel 3\" cerda natural", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bandeja para rodillo plástica", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Espátula acero 8cm", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Lija al agua 150 x hoja", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 200, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta de pintor 24mm x 50m", "category_slug": "rodillos-pinceles-ferret", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Candado bronce 40mm", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Candado bronce 50mm", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cerradura de embutir para puerta", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cerrojo de seguridad doble paleta", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Manija exterior puerta entrada", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Picaporte doble acción cromado", "category_slug": "candados-cerraduras", "brand": null, "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Bisagra 3\" acero x par", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bisagra 4\" acero x par", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 700, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bisagra cierra-puertas aérea", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Riel para cajón 350mm x par", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Riel para cajón 450mm x par", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Escuadra refuerzo 3\" x4", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Soporte mensula 20cm x par", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Gancho perchero cromado x10", "category_slug": "bisagras-herrajes", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "La Gotita adhesivo instantáneo 3g", "category_slug": "cintas-adhesivos-ferret", "brand": "La Gotita", "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Poxipol transparente 14ml", "category_slug": "cintas-adhesivos-ferret", "brand": "Poxipol", "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Poxipol gris metálico 70ml", "category_slug": "cintas-adhesivos-ferret", "brand": "Poxipol", "price_reference": 5500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Silicona acetica transparente 280ml", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Silicona neutra blanca 280ml", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta ducto 48mm x 9m", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta aisladora PVC 10m", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cinta doble faz espuma 19mm x 5m", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cola vinílica 1kg", "category_slug": "cintas-adhesivos-ferret", "brand": "Akapol", "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cemento de contacto 1L", "category_slug": "cintas-adhesivos-ferret", "brand": "Fortex", "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Masilla para vidrios 1kg", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Sellador acrílico blanco 280ml", "category_slug": "cintas-adhesivos-ferret", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},

  {"name": "Cuchilla tramontina 25mm x10 hojas", "category_slug": "herramientas-manuales", "brand": "Tramontina", "price_reference": 1500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Trincheta retráctil profesional", "category_slug": "herramientas-manuales", "brand": "Stanley", "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Espátula acero inoxidable 15cm", "category_slug": "herramientas-manuales", "brand": "Tramontina", "price_reference": 3000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llana lisa acero 28cm", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Llana dentada 28cm", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Cuchara de albañil 8\"", "category_slug": "herramientas-manuales", "brand": "Tramontina", "price_reference": 4000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Balde albañil 12L", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Carretilla obra reforzada", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pala ancha punta corazón", "category_slug": "herramientas-manuales", "brand": "Tramontina", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pico con mango", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 9000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Tijera de podar bypass", "category_slug": "herramientas-manuales", "brand": "Bahco", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pistola para pintar eléctrica 350W", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 25000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Soldador de estaño 40W", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 4000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Estaño 1mm x 250g", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Multímetro digital básico", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pistola engrampadora manual", "category_slug": "herramientas-manuales", "brand": "Stanley", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Grampas para engrampadora 8mm x1000", "category_slug": "herramientas-manuales", "brand": "Stanley", "price_reference": 2000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Pistola aplicadora silicona", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Remachadora manual", "category_slug": "herramientas-manuales", "brand": "Hamilton", "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Morsa de banco 4\"", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 15000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Prensa sargento 12\"", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Flexómetro láser Bosch 20m", "category_slug": "herramientas-manuales", "brand": "Bosch", "price_reference": 35000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Compresor de aire 50L Lusqtoff", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 180000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Motosierra a nafta Lusqtoff 18\"", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 250000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Bordeadora a nafta Lusqtoff", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 120000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Hidrolavadora 1500W Lusqtoff", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 150000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Soldadora inverter 200A Lusqtoff", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 180000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Electrodos 6013 2.5mm x1kg", "category_slug": "herramientas-manuales", "brand": "Conarco", "price_reference": 5000, "unit": "kg", "sku_prefix": "FERRET"},
  {"name": "Máscara fotosensible para soldar", "category_slug": "herramientas-manuales", "brand": "Lusqtoff", "price_reference": 25000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Guantes descarne para soldar", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Antiparras de seguridad transparentes", "category_slug": "herramientas-manuales", "brand": "Libus", "price_reference": 2500, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Guantes de látex multiuso par", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Faja lumbar de trabajo", "category_slug": "herramientas-manuales", "brand": "FMT", "price_reference": 8000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Escalera aluminio tijera 5 escalones", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 45000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Escalera aluminio extensible 12 escalones", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 85000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Caja de herramientas plástica 19\"", "category_slug": "herramientas-manuales", "brand": "Stanley", "price_reference": 12000, "unit": "unidad", "sku_prefix": "FERRET"},
  {"name": "Organizador plástico 15 compartimentos", "category_slug": "herramientas-manuales", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "FERRET"}
]'::jsonb,
updated_at = CURRENT_TIMESTAMP
WHERE business_type_id = (SELECT id FROM business_types WHERE code = 'ferreteria') AND is_default = true;
