-- =============================================================================
-- SEED 035: Catálogo masivo de kiosco argentino (~250 productos reales)
-- Actualiza business_type_templates.products para 'kiosco'
-- Marcas nacionales reales: Arcor, Bagley, Terrabusi, Coca-Cola, Quilmes,
--   Guaymallén, Rasta, Lay's, Marlboro, Beldent, Felfort, Milka, Cadbury, etc.
-- Precios referencia: abril 2026 (precio kiosco/retail)
-- =============================================================================

UPDATE business_type_templates
SET products = '[
  {"name": "Alfajor Rasta triple chocolate", "category_slug": "alfajores", "brand": "Rasta", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Rasta triple blanco", "category_slug": "alfajores", "brand": "Rasta", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Guaymallén triple chocolate", "category_slug": "alfajores", "brand": "Guaymallen", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Guaymallén triple blanco", "category_slug": "alfajores", "brand": "Guaymallen", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Guaymallén simple chocolate", "category_slug": "alfajores", "brand": "Guaymallen", "price_reference": 300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Fantoche triple", "category_slug": "alfajores", "brand": "Fantoche", "price_reference": 900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Fantoche simple", "category_slug": "alfajores", "brand": "Fantoche", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Jorgito negro", "category_slug": "alfajores", "brand": "Jorgito", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Jorgito blanco", "category_slug": "alfajores", "brand": "Jorgito", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Capitán del Espacio triple", "category_slug": "alfajores", "brand": "Capitan del Espacio", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Tatín triple", "category_slug": "alfajores", "brand": "Tatin", "price_reference": 800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Tatín simple", "category_slug": "alfajores", "brand": "Tatin", "price_reference": 450, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Aguila brownie", "category_slug": "alfajores", "brand": "Aguila", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Gula triple chocolate", "category_slug": "alfajores", "brand": "Gula", "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Havanna 70% cacao", "category_slug": "alfajores", "brand": "Havanna", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Cachafaz chocolate", "category_slug": "alfajores", "brand": "Cachafaz", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Terrabusi triple", "category_slug": "alfajores", "brand": "Terrabusi", "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Milka mousse", "category_slug": "alfajores", "brand": "Milka", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Block chocolate", "category_slug": "alfajores", "brand": "Felfort", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alfajor Ser cereal", "category_slug": "alfajores", "brand": "Ser", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Bon o Bon chocolate", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Bon o Bon blanco", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Rocklets confites chocolate 40g", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Shot caramelo relleno", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "2 Corazones chocolate con leche", "category_slug": "golosinas", "brand": "Felfort", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Kinder Sorpresa", "category_slug": "golosinas", "brand": "Ferrero", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Kinder Bueno", "category_slug": "golosinas", "brand": "Ferrero", "price_reference": 3800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Rhodesia oblea bañada", "category_slug": "golosinas", "brand": "Terrabusi", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Tita oblea chocolate", "category_slug": "golosinas", "brand": "Terrabusi", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Turron Arcor maní 25g", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mantecol 110g", "category_slug": "golosinas", "brand": "Mantecol", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Chupetín Pico Dulce", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Paleta Mumu frutilla", "category_slug": "golosinas", "brand": "Arcor", "price_reference": 400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pastillas DRF menta", "category_slug": "golosinas", "brand": "DRF", "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Cofler chocolate con leche 60g", "category_slug": "chocolates", "brand": "Arcor", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cofler aireado 55g", "category_slug": "chocolates", "brand": "Arcor", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cofler Block chocolate 38g", "category_slug": "chocolates", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Milka chocolate con leche 55g", "category_slug": "chocolates", "brand": "Milka", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Milka Oreo 55g", "category_slug": "chocolates", "brand": "Milka", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Milka Leger 100g", "category_slug": "chocolates", "brand": "Milka", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cadbury barra chocolate con leche 72g", "category_slug": "chocolates", "brand": "Cadbury", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Toblerone chocolate con leche 100g", "category_slug": "chocolates", "brand": "Toblerone", "price_reference": 5500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Aguila chocolate amargo 100g", "category_slug": "chocolates", "brand": "Aguila", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Georgalos Maní con Chocolate 80g", "category_slug": "chocolates", "brand": "Georgalos", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Arcor chocolate blanco 25g", "category_slug": "chocolates", "brand": "Arcor", "price_reference": 600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Chocolate Aguila para taza 100g", "category_slug": "chocolates", "brand": "Aguila", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Caramelos Media Hora tubo", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Menthoplus strong", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Menthoplus cherry", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Flynn Paff tutti frutti", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Flynn Paff uva", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Beldent Infinit menta", "category_slug": "caramelos-chicles", "brand": "Beldent", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Beldent Infinit sandía", "category_slug": "caramelos-chicles", "brand": "Beldent", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Topline Seven menta", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Topline Seven frutilla", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Bazooka chicle globo", "category_slug": "caramelos-chicles", "brand": "Bazooka", "price_reference": 200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Bubbaloo frutilla", "category_slug": "caramelos-chicles", "brand": "Cadbury", "price_reference": 250, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Sugus surtidos 25g", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 350, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Butter Toffees surtidos 150g", "category_slug": "caramelos-chicles", "brand": "Arcor", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Halls mentol", "category_slug": "caramelos-chicles", "brand": "Cadbury", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Mogul gomitas frutales 50g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mogul gomitas ácidas 50g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mogul tiburones 50g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mogul Moras 50g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mogul corazones 50g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Gomitas Trolli hamburguesa 50g", "category_slug": "gomitas-malvaviscos", "brand": "Trolli", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Malvaviscos Marengo 100g", "category_slug": "gomitas-malvaviscos", "brand": "Marengo", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Malvaviscos Guolis 100g", "category_slug": "gomitas-malvaviscos", "brand": "Arcor", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Coca-Cola 500ml", "category_slug": "gaseosas", "brand": "Coca-Cola", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Coca-Cola Zero 500ml", "category_slug": "gaseosas", "brand": "Coca-Cola", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Coca-Cola 1.5L", "category_slug": "gaseosas", "brand": "Coca-Cola", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Coca-Cola 2.25L", "category_slug": "gaseosas", "brand": "Coca-Cola", "price_reference": 4200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Coca-Cola lata 354ml", "category_slug": "gaseosas", "brand": "Coca-Cola", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Sprite 500ml", "category_slug": "gaseosas", "brand": "Sprite", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Sprite 1.5L", "category_slug": "gaseosas", "brand": "Sprite", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Sprite lata 354ml", "category_slug": "gaseosas", "brand": "Sprite", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Fanta naranja 500ml", "category_slug": "gaseosas", "brand": "Fanta", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Fanta naranja lata 354ml", "category_slug": "gaseosas", "brand": "Fanta", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pepsi 500ml", "category_slug": "gaseosas", "brand": "Pepsi", "price_reference": 1700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pepsi lata 354ml", "category_slug": "gaseosas", "brand": "Pepsi", "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "7UP 1.5L", "category_slug": "gaseosas", "brand": "7UP", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Manaos cola 2.25L", "category_slug": "gaseosas", "brand": "Manaos", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Manaos naranja 2.25L", "category_slug": "gaseosas", "brand": "Manaos", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Manaos uva 2.25L", "category_slug": "gaseosas", "brand": "Manaos", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Paso de los Toros pomelo 500ml", "category_slug": "gaseosas", "brand": "Paso de los Toros", "price_reference": 1900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Paso de los Toros tónica 1.5L", "category_slug": "gaseosas", "brand": "Paso de los Toros", "price_reference": 3000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Schweppes tónica 500ml", "category_slug": "gaseosas", "brand": "Schweppes", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Agua Villavicencio sin gas 500ml", "category_slug": "aguas-saborizadas", "brand": "Villavicencio", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agua Villavicencio con gas 500ml", "category_slug": "aguas-saborizadas", "brand": "Villavicencio", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agua Villavicencio 1.5L sin gas", "category_slug": "aguas-saborizadas", "brand": "Villavicencio", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agua Glaciar sin gas 500ml", "category_slug": "aguas-saborizadas", "brand": "Glaciar", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agua Villa del Sur sin gas 1.5L", "category_slug": "aguas-saborizadas", "brand": "Villa del Sur", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agua Eco de los Andes 500ml", "category_slug": "aguas-saborizadas", "brand": "Eco de los Andes", "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Levité pomelo 500ml", "category_slug": "aguas-saborizadas", "brand": "Villa del Sur", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Levité manzana 500ml", "category_slug": "aguas-saborizadas", "brand": "Villa del Sur", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Ser agua saborizada pomelo 500ml", "category_slug": "aguas-saborizadas", "brand": "Ser", "price_reference": 1700, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Jugo Baggio naranja 200ml", "category_slug": "jugos", "brand": "Baggio", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jugo Baggio manzana 200ml", "category_slug": "jugos", "brand": "Baggio", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jugo Baggio durazno 200ml", "category_slug": "jugos", "brand": "Baggio", "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jugo Baggio multifruta 1L", "category_slug": "jugos", "brand": "Baggio", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jugo Cepita naranja 200ml", "category_slug": "jugos", "brand": "Cepita", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jugo Cepita multifruta 1L", "category_slug": "jugos", "brand": "Cepita", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Ades soja manzana 200ml", "category_slug": "jugos", "brand": "Ades", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Tang naranja sobre 20g", "category_slug": "jugos", "brand": "Tang", "price_reference": 400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Clight limonada sobre", "category_slug": "jugos", "brand": "Clight", "price_reference": 450, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Speed energizante 250ml", "category_slug": "energizantes", "brand": "Speed", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Speed energizante 473ml", "category_slug": "energizantes", "brand": "Speed", "price_reference": 3000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Speed Unlimited 473ml", "category_slug": "energizantes", "brand": "Speed", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Red Bull 250ml", "category_slug": "energizantes", "brand": "Red Bull", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Red Bull Sugar Free 250ml", "category_slug": "energizantes", "brand": "Red Bull", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Monster Energy 473ml", "category_slug": "energizantes", "brand": "Monster", "price_reference": 3800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Monster Ultra 473ml", "category_slug": "energizantes", "brand": "Monster", "price_reference": 3800, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Powerade Mountain Blast 500ml", "category_slug": "jugos", "brand": "Powerade", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Gatorade manzana 500ml", "category_slug": "jugos", "brand": "Gatorade", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Gatorade tropical 500ml", "category_slug": "jugos", "brand": "Gatorade", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Cerveza Quilmes 473ml lata", "category_slug": "cervezas", "brand": "Quilmes", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Quilmes 1L retornable", "category_slug": "cervezas", "brand": "Quilmes", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Quilmes Stout 473ml", "category_slug": "cervezas", "brand": "Quilmes", "price_reference": 2400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Brahma 473ml lata", "category_slug": "cervezas", "brand": "Brahma", "price_reference": 1900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Brahma 1L retornable", "category_slug": "cervezas", "brand": "Brahma", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Stella Artois 473ml lata", "category_slug": "cervezas", "brand": "Stella Artois", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Imperial 473ml lata", "category_slug": "cervezas", "brand": "Imperial", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Andes Origen 473ml lata", "category_slug": "cervezas", "brand": "Andes", "price_reference": 2600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Patagonia Amber Lager 473ml", "category_slug": "cervezas", "brand": "Patagonia", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Corona 355ml", "category_slug": "cervezas", "brand": "Corona", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerveza Heineken 473ml lata", "category_slug": "cervezas", "brand": "Heineken", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Marlboro Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Marlboro", "price_reference": 6500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Marlboro Gold Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Marlboro", "price_reference": 6500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Camel Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Camel", "price_reference": 6000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Philip Morris Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Philip Morris", "price_reference": 5000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lucky Strike Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Lucky Strike", "price_reference": 5500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Chesterfield Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Chesterfield", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "L&M Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "L&M", "price_reference": 4200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Jockey Club Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Jockey", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Red Point Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Red Point", "price_reference": 16600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Red Point Convertible 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Red Point", "price_reference": 18500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Viceroy Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Viceroy", "price_reference": 4000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Master Atado 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Master", "price_reference": 12800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Dolchester Box 20 unidades", "category_slug": "cigarrillos-tabaco", "brand": "Dolchester", "price_reference": 15600, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Lay''s clásicas 75g", "category_slug": "papas-fritas", "brand": "Lay''s", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lay''s jamón serrano 75g", "category_slug": "papas-fritas", "brand": "Lay''s", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lay''s corte americano 75g", "category_slug": "papas-fritas", "brand": "Lay''s", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lay''s onduladas 75g", "category_slug": "papas-fritas", "brand": "Lay''s", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pringles original 124g", "category_slug": "papas-fritas", "brand": "Pringles", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pringles crema y cebolla 124g", "category_slug": "papas-fritas", "brand": "Pringles", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pringles cheddar 124g", "category_slug": "papas-fritas", "brand": "Pringles", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pehuamar papas fritas 55g", "category_slug": "papas-fritas", "brand": "Pehuamar", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Krachitos papas tubo 65g", "category_slug": "papas-fritas", "brand": "Krachitos", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Palitos salados Pehuamar 120g", "category_slug": "palitos-chizitos", "brand": "Pehuamar", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Chizitos Pehuamar 60g", "category_slug": "palitos-chizitos", "brand": "Pehuamar", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cheetos 75g", "category_slug": "palitos-chizitos", "brand": "Cheetos", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Palitos de la Selva 200g", "category_slug": "palitos-chizitos", "brand": "Palitos de la Selva", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Palitos salados DOS 100g", "category_slug": "palitos-chizitos", "brand": "DOS", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Palitos salados Maestro Cubano 100g", "category_slug": "palitos-chizitos", "brand": "Maestro Cubano", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Saladix pizza 100g", "category_slug": "snacks", "brand": "Saladix", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Saladix jamón y queso 100g", "category_slug": "snacks", "brand": "Saladix", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Saladix queso 100g", "category_slug": "snacks", "brand": "Saladix", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Saladix calabresa 100g", "category_slug": "snacks", "brand": "Saladix", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Twistos integrales 100g", "category_slug": "snacks", "brand": "Twistos", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Twistos queso 100g", "category_slug": "snacks", "brand": "Twistos", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Twistos jamón 100g", "category_slug": "snacks", "brand": "Twistos", "price_reference": 1600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Doritos queso 75g", "category_slug": "snacks", "brand": "Doritos", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Doritos dippas 75g", "category_slug": "snacks", "brand": "Doritos", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Maní con piel Pehuamar 120g", "category_slug": "frutos-secos", "brand": "Pehuamar", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Maní pelado Pehuamar 120g", "category_slug": "frutos-secos", "brand": "Pehuamar", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Maní salado Pehuamar 120g", "category_slug": "frutos-secos", "brand": "Pehuamar", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mix de frutos secos Georgalos 100g", "category_slug": "frutos-secos", "brand": "Georgalos", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Almendras Georgalos 100g", "category_slug": "frutos-secos", "brand": "Georgalos", "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Castañas de cajú 80g", "category_slug": "frutos-secos", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Nuez pecán 80g", "category_slug": "frutos-secos", "brand": null, "price_reference": 5500, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Criollitas galletitas 100g", "category_slug": "galletitas-saladas", "brand": "Bagley", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Traviata galletitas 100g", "category_slug": "galletitas-saladas", "brand": "Bagley", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Rex galletitas crackers 100g", "category_slug": "galletitas-saladas", "brand": "Bagley", "price_reference": 1100, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lincoln galletitas integrales 153g", "category_slug": "galletitas-saladas", "brand": "Terrabusi", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cerealitas galletitas 200g", "category_slug": "galletitas-saladas", "brand": "Bagley", "price_reference": 1700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas de arroz 100g", "category_slug": "galletitas-saladas", "brand": null, "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Don Satur saladas 200g", "category_slug": "galletitas-saladas", "brand": "Don Satur", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Don Satur bizcocho dulce 200g", "category_slug": "galletitas-saladas", "brand": "Don Satur", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Oreo chocolate 117g", "category_slug": "galletitas-dulces", "brand": "Oreo", "price_reference": 1900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Oreo doble 126g", "category_slug": "galletitas-dulces", "brand": "Oreo", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Chocolinas 170g", "category_slug": "galletitas-dulces", "brand": "Terrabusi", "price_reference": 1700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Rumba galletitas chocolate 112g", "category_slug": "galletitas-dulces", "brand": "Arcor", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Opera galletitas 100g", "category_slug": "galletitas-dulces", "brand": "Bagley", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Oblea Opera triple 100g", "category_slug": "galletitas-dulces", "brand": "Bagley", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Merengadas galletitas 100g", "category_slug": "galletitas-dulces", "brand": "Bagley", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Mana galletitas vainilla 169g", "category_slug": "galletitas-dulces", "brand": "Arcor", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Canale bizcochos dulces 200g", "category_slug": "galletitas-dulces", "brand": "Terrabusi", "price_reference": 1400, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Galletitas surtidas Terrabusi 400g", "category_slug": "galletitas", "brand": "Terrabusi", "price_reference": 3000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas Toddy 126g", "category_slug": "galletitas", "brand": "Toddy", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas Pepitos chocolate 119g", "category_slug": "galletitas", "brand": "Pepitos", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas Express chocolate 100g", "category_slug": "galletitas", "brand": "Bagley", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas Sonrisas 107g", "category_slug": "galletitas", "brand": "Bagley", "price_reference": 1300, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Galletitas Mantecol 120g", "category_slug": "galletitas", "brand": "Mantecol", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Variedad galletitas surtidas 300g", "category_slug": "galletitas", "brand": "Terrabusi", "price_reference": 2800, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Encendedor Bic mini", "category_slug": "encendedores", "brand": "Bic", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Encendedor Bic Maxi", "category_slug": "encendedores", "brand": "Bic", "price_reference": 2200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Encendedor descartable chico", "category_slug": "encendedores", "brand": null, "price_reference": 600, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Encendedor descartable grande", "category_slug": "encendedores", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Encendedor recargable metálico", "category_slug": "encendedores", "brand": null, "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Fósforos largos x1 caja", "category_slug": "encendedores", "brand": null, "price_reference": 500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Fósforos cortos x1 caja", "category_slug": "encendedores", "brand": null, "price_reference": 400, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Pilas AA Duracell x2", "category_slug": "pilas-baterias", "brand": "Duracell", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pilas AAA Duracell x2", "category_slug": "pilas-baterias", "brand": "Duracell", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pilas AA Energizer x2", "category_slug": "pilas-baterias", "brand": "Energizer", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pilas AAA Energizer x2", "category_slug": "pilas-baterias", "brand": "Energizer", "price_reference": 3500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pilas AA genéricas x4", "category_slug": "pilas-baterias", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pila 9V genérica", "category_slug": "pilas-baterias", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pilas CR2032 botón", "category_slug": "pilas-baterias", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Preservativos Prime x3", "category_slug": "higiene-personal", "brand": "Prime", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Preservativos Tulipán x3", "category_slug": "higiene-personal", "brand": "Tulipan", "price_reference": 2500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pañuelos tissue pocket pack x10", "category_slug": "higiene-personal", "brand": "Elite", "price_reference": 800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Pañuelos tissue pocket pack x6", "category_slug": "higiene-personal", "brand": "Kleenex", "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Toallitas húmedas Huggies x10", "category_slug": "higiene-personal", "brand": "Huggies", "price_reference": 1800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Alcohol en gel 60ml", "category_slug": "higiene-personal", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Protector labial Labello", "category_slug": "higiene-personal", "brand": "Labello", "price_reference": 3200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Curitas Nexcare x10", "category_slug": "higiene-personal", "brand": "Nexcare", "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Desodorante Rexona sachet", "category_slug": "higiene-personal", "brand": "Rexona", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},

  {"name": "Bolsa de residuos 45x60 x10", "category_slug": "varios-kiosco", "brand": null, "price_reference": 1000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Bolsa de residuos 60x90 x10", "category_slug": "varios-kiosco", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cinta adhesiva transparente", "category_slug": "varios-kiosco", "brand": null, "price_reference": 900, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Rollo de papel higiénico individual", "category_slug": "varios-kiosco", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Servilletas x100", "category_slug": "varios-kiosco", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Lapicera Bic cristal", "category_slug": "varios-kiosco", "brand": "Bic", "price_reference": 700, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Auriculares in-ear genéricos", "category_slug": "varios-kiosco", "brand": null, "price_reference": 4000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cable USB-C carga genérico", "category_slug": "varios-kiosco", "brand": null, "price_reference": 4500, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Cargador portátil genérico 5000mAh", "category_slug": "varios-kiosco", "brand": null, "price_reference": 10000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Tarjeta SUBE", "category_slug": "varios-kiosco", "brand": null, "price_reference": 4000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Agenda pocket", "category_slug": "varios-kiosco", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "KIOSK"},
  {"name": "Carilina pañuelos descartables x6", "category_slug": "varios-kiosco", "brand": "Carilina", "price_reference": 1200, "unit": "unidad", "sku_prefix": "KIOSK"}
]'::jsonb,
updated_at = CURRENT_TIMESTAMP
WHERE business_type_id = (SELECT id FROM business_types WHERE code = 'kiosco') AND is_default = true;
