-- =============================================================================
-- SEED 037: Catálogo masivo de perfumería (~250 productos reales argentinos)
-- Actualiza business_type_templates.products para 'perfumeria'
-- Marcas reales: Natura, Avon, L'Oréal, Nivea, Dove, TRESemmé, Revlon,
--   Maybelline, Sedal, Pantene, Rexona, Axe, Gillette, La Roche-Posay,
--   Antonio Banderas, Benetton, Colgate-Palmolive, Plusbelle, Suave,
--   Garnier, Schwarzkopf, Eucerin, Neutrogena, Head & Shoulders, etc.
-- =============================================================================

UPDATE business_type_templates
SET products = '[
  {"name": "Perfume Natura Luna 50ml", "category_slug": "perfumes-mujer", "brand": "Natura", "price_reference": 28000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Natura Ekos Flor do Luar 50ml", "category_slug": "perfumes-mujer", "brand": "Natura", "price_reference": 32000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Natura Humor 75ml", "category_slug": "perfumes-mujer", "brand": "Natura", "price_reference": 25000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Avon Far Away 50ml", "category_slug": "perfumes-mujer", "brand": "Avon", "price_reference": 18000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Avon Little Black Dress 50ml", "category_slug": "perfumes-mujer", "brand": "Avon", "price_reference": 16000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Avon Passion Dance 50ml", "category_slug": "perfumes-mujer", "brand": "Avon", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Ciel EDT 50ml", "category_slug": "perfumes-mujer", "brand": "Ciel", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Kevingston Donna 50ml", "category_slug": "perfumes-mujer", "brand": "Kevingston", "price_reference": 15000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Prune EDT 50ml", "category_slug": "perfumes-mujer", "brand": "Prüne", "price_reference": 22000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Paula Cahen D''Anvers EDT 60ml", "category_slug": "perfumes-mujer", "brand": "Paula Cahen D''Anvers", "price_reference": 20000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Benetton United Dreams Stay Positive 80ml", "category_slug": "perfumes-mujer", "brand": "Benetton", "price_reference": 24000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Benetton Colors Rose 80ml", "category_slug": "perfumes-mujer", "brand": "Benetton", "price_reference": 22000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Perfume Antonio Banderas The Secret 100ml", "category_slug": "perfumes-hombre", "brand": "Antonio Banderas", "price_reference": 26000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Antonio Banderas King of Seduction 100ml", "category_slug": "perfumes-hombre", "brand": "Antonio Banderas", "price_reference": 28000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Antonio Banderas Blue Seduction 100ml", "category_slug": "perfumes-hombre", "brand": "Antonio Banderas", "price_reference": 24000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Antonio Banderas The Icon 100ml", "category_slug": "perfumes-hombre", "brand": "Antonio Banderas", "price_reference": 30000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Kevingston 1989 EDT 60ml", "category_slug": "perfumes-hombre", "brand": "Kevingston", "price_reference": 15000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Patrichs Noir EDT 100ml", "category_slug": "perfumes-hombre", "brand": "Patrichs", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Kevin EDT 60ml", "category_slug": "perfumes-hombre", "brand": "Kevin", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Colbert EDT 60ml", "category_slug": "perfumes-hombre", "brand": "Colbert", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Bross London EDT 100ml", "category_slug": "perfumes-hombre", "brand": "Bross London", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Benetton United Dreams Be Strong 100ml", "category_slug": "perfumes-hombre", "brand": "Benetton", "price_reference": 24000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Natura Kaiak Extremo 100ml", "category_slug": "perfumes-hombre", "brand": "Natura", "price_reference": 30000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Natura Homem 100ml", "category_slug": "perfumes-hombre", "brand": "Natura", "price_reference": 28000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Perfume Benetton United Dreams Together 80ml", "category_slug": "perfumes-unisex", "brand": "Benetton", "price_reference": 22000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Perfume Natura Ekos Frescor 100ml", "category_slug": "perfumes-unisex", "brand": "Natura", "price_reference": 26000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Colonia Avon Deo Colonia Soft Musk 50ml", "category_slug": "perfumes-unisex", "brand": "Avon", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Body Splash Avon Senses 250ml", "category_slug": "perfumes-unisex", "brand": "Avon", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Body Splash Natura Tododia 200ml", "category_slug": "perfumes-unisex", "brand": "Natura", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Colonia Etiquet pour Homme 200ml", "category_slug": "perfumes-unisex", "brand": "Etiquet", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Base Líquida Maybelline Fit Me Matte 30ml", "category_slug": "base-correctores", "brand": "Maybelline", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Base Líquida Maybelline SuperStay 30ml", "category_slug": "base-correctores", "brand": "Maybelline", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Corrector Maybelline Instant Age Rewind 6ml", "category_slug": "base-correctores", "brand": "Maybelline", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Corrector Maybelline Fit Me 6.8ml", "category_slug": "base-correctores", "brand": "Maybelline", "price_reference": 8500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Base Líquida Revlon ColorStay 30ml", "category_slug": "base-correctores", "brand": "Revlon", "price_reference": 16000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Base Revlon Candid 30ml", "category_slug": "base-correctores", "brand": "Revlon", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Base L''Oréal Infallible 24H Fresh Wear 30ml", "category_slug": "base-correctores", "brand": "L''Oréal", "price_reference": 18000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Corrector L''Oréal Infallible Full Wear 10ml", "category_slug": "base-correctores", "brand": "L''Oréal", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Polvo Compacto Maybelline Fit Me 12g", "category_slug": "base-correctores", "brand": "Maybelline", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Polvo Compacto Revlon ColorStay 8.4g", "category_slug": "base-correctores", "brand": "Revlon", "price_reference": 13000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Labial Maybelline SuperStay Matte Ink 5ml", "category_slug": "labiales", "brand": "Maybelline", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial Maybelline SuperStay Vinyl Ink 4.2ml", "category_slug": "labiales", "brand": "Maybelline", "price_reference": 11000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Brillo Labial Maybelline Lifter Gloss 5.4ml", "category_slug": "labiales", "brand": "Maybelline", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial Revlon Super Lustrous 4.2g", "category_slug": "labiales", "brand": "Revlon", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial Revlon ColorStay Ultimate 2.55g", "category_slug": "labiales", "brand": "Revlon", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Delineador Labial Revlon ColorStay 0.28g", "category_slug": "labiales", "brand": "Revlon", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial L''Oréal Color Riche 3.6g", "category_slug": "labiales", "brand": "L''Oréal", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial Avon Power Stay 16H 7ml", "category_slug": "labiales", "brand": "Avon", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Labial Natura Una 3.5g", "category_slug": "labiales", "brand": "Natura", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Máscara de Pestañas Maybelline Sky High 7.2ml", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Máscara de Pestañas Maybelline Lash Sensational 9.5ml", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Máscara de Pestañas Maybelline Colossal 10.7ml", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Delineador Maybelline Hyper Easy Brush Tip", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Delineador Maybelline Master Precise", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Paleta de Sombras Maybelline The Nudes 9.6g", "category_slug": "ojos", "brand": "Maybelline", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Máscara de Pestañas Revlon Mega Multiplier 8.5ml", "category_slug": "ojos", "brand": "Revlon", "price_reference": 11000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Sombra Revlon ColorStay Crème 5.2g", "category_slug": "ojos", "brand": "Revlon", "price_reference": 8500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Delineador Revlon ColorStay Skinny Liquid Liner", "category_slug": "ojos", "brand": "Revlon", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Lápiz Delineador L''Oréal Le Khol", "category_slug": "ojos", "brand": "L''Oréal", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Máscara L''Oréal Voluminous Lash Paradise", "category_slug": "ojos", "brand": "L''Oréal", "price_reference": 13000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Shampoo Sedal Crema Balance 650ml", "category_slug": "shampoo", "brand": "Sedal", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Sedal Ceramidas 650ml", "category_slug": "shampoo", "brand": "Sedal", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Sedal Reconstrucción Estructural 650ml", "category_slug": "shampoo", "brand": "Sedal", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Pantene Pro-V Restauración 400ml", "category_slug": "shampoo", "brand": "Pantene", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Pantene Pro-V Liso Extremo 400ml", "category_slug": "shampoo", "brand": "Pantene", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Pantene Miracles 510ml", "category_slug": "shampoo", "brand": "Pantene", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo TRESemmé Hidratación Profunda 750ml", "category_slug": "shampoo", "brand": "TRESemmé", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo TRESemmé Blindaje Anti-Quiebre 750ml", "category_slug": "shampoo", "brand": "TRESemmé", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Dove Regeneración Extrema 400ml", "category_slug": "shampoo", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Dove Óleo Nutrición 400ml", "category_slug": "shampoo", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Head & Shoulders Limpieza Renovadora 375ml", "category_slug": "shampoo", "brand": "Head & Shoulders", "price_reference": 6200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Head & Shoulders Men 3en1 375ml", "category_slug": "shampoo", "brand": "Head & Shoulders", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo L''Oréal Elvive Óleo Extraordinario 400ml", "category_slug": "shampoo", "brand": "L''Oréal", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo L''Oréal Elvive Arcilla Purificante 400ml", "category_slug": "shampoo", "brand": "L''Oréal", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Plusbelle Nutrición 1000ml", "category_slug": "shampoo", "brand": "Plusbelle", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Suave Reconstrucción Completa 930ml", "category_slug": "shampoo", "brand": "Suave", "price_reference": 4200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Schwarzkopf Gliss Ultimate Repair 400ml", "category_slug": "shampoo", "brand": "Schwarzkopf", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Shampoo Garnier Fructis Crece Fuerte 350ml", "category_slug": "shampoo", "brand": "Garnier", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Acondicionador Sedal Crema Balance 650ml", "category_slug": "acondicionador", "brand": "Sedal", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Sedal Ceramidas 650ml", "category_slug": "acondicionador", "brand": "Sedal", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Pantene Pro-V Restauración 400ml", "category_slug": "acondicionador", "brand": "Pantene", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Pantene Pro-V Liso Extremo 400ml", "category_slug": "acondicionador", "brand": "Pantene", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador TRESemmé Hidratación Profunda 750ml", "category_slug": "acondicionador", "brand": "TRESemmé", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Dove Regeneración Extrema 400ml", "category_slug": "acondicionador", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Dove Óleo Nutrición 400ml", "category_slug": "acondicionador", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador L''Oréal Elvive Óleo Extraordinario 400ml", "category_slug": "acondicionador", "brand": "L''Oréal", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Head & Shoulders Limpieza Renovadora 375ml", "category_slug": "acondicionador", "brand": "Head & Shoulders", "price_reference": 6200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Plusbelle Nutrición 1000ml", "category_slug": "acondicionador", "brand": "Plusbelle", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Suave Reconstrucción Completa 930ml", "category_slug": "acondicionador", "brand": "Suave", "price_reference": 4200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Garnier Fructis Crece Fuerte 350ml", "category_slug": "acondicionador", "brand": "Garnier", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Acondicionador Schwarzkopf Gliss Ultimate Repair 400ml", "category_slug": "acondicionador", "brand": "Schwarzkopf", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Crema de Tratamiento Sedal Crema Balance 300g", "category_slug": "tratamiento-capilar", "brand": "Sedal", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema de Tratamiento Pantene 3 Minute Miracle 170ml", "category_slug": "tratamiento-capilar", "brand": "Pantene", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema de Peinar TRESemmé Hidratación Profunda 300ml", "category_slug": "tratamiento-capilar", "brand": "TRESemmé", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Ampolla Capilar Sedal Ceramidas 15ml x3", "category_slug": "tratamiento-capilar", "brand": "Sedal", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Aceite Capilar L''Oréal Elvive Óleo Extraordinario 100ml", "category_slug": "tratamiento-capilar", "brand": "L''Oréal", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema para Peinar Dove Regeneración Extrema 300ml", "category_slug": "tratamiento-capilar", "brand": "Dove", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tratamiento Schwarzkopf Gliss Mascarilla 300ml", "category_slug": "tratamiento-capilar", "brand": "Schwarzkopf", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema de Peinar Plusbelle Rizos Definidos 300ml", "category_slug": "tratamiento-capilar", "brand": "Plusbelle", "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Sérum Capilar Pantene Pro-V Miracles 100ml", "category_slug": "tratamiento-capilar", "brand": "Pantene", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Spray Protector Térmico TRESemmé 120ml", "category_slug": "tratamiento-capilar", "brand": "TRESemmé", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tintura Permanente Schwarzkopf Palette", "category_slug": "tratamiento-capilar", "brand": "Schwarzkopf", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tintura L''Oréal Casting Creme Gloss", "category_slug": "tratamiento-capilar", "brand": "L''Oréal", "price_reference": 8500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tintura L''Oréal Imédia Excellence", "category_slug": "tratamiento-capilar", "brand": "L''Oréal", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tintura Issue Crazy Colors", "category_slug": "tratamiento-capilar", "brand": "Issue", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Crema Corporal Nivea Creme 250ml", "category_slug": "cremas-corporales", "brand": "Nivea", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Nivea Soft 200ml", "category_slug": "cremas-corporales", "brand": "Nivea", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Nivea Body Milk 400ml", "category_slug": "cremas-corporales", "brand": "Nivea", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Dove Nutrición Esencial 400ml", "category_slug": "cremas-corporales", "brand": "Dove", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Dove DermaSpa 300ml", "category_slug": "cremas-corporales", "brand": "Dove", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Natura Tododia Frambuesa 400ml", "category_slug": "cremas-corporales", "brand": "Natura", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Natura Ekos Maracuyá 400ml", "category_slug": "cremas-corporales", "brand": "Natura", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Avon Care Leche y Miel 400ml", "category_slug": "cremas-corporales", "brand": "Avon", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Hinds Anti-Age 350ml", "category_slug": "cremas-corporales", "brand": "Hinds", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Corporal Hinds Almendras y Vitamina E 350ml", "category_slug": "cremas-corporales", "brand": "Hinds", "price_reference": 4200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Vaselina en Crema Vasenol Nutrición Total 400ml", "category_slug": "cremas-corporales", "brand": "Vasenol", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Protector Solar Nivea Sun Protect & Moisturize FPS50 200ml", "category_slug": "cremas-corporales", "brand": "Nivea", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Protector Solar La Roche-Posay Anthelios FPS50 50ml", "category_slug": "cremas-corporales", "brand": "La Roche-Posay", "price_reference": 22000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Desodorante Rexona Clinical Crema 48g", "category_slug": "desodorantes", "brand": "Rexona", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Rexona Aerosol Antibacterial 150ml", "category_slug": "desodorantes", "brand": "Rexona", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Rexona Roll-On Invisible 50ml", "category_slug": "desodorantes", "brand": "Rexona", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Rexona Men V8 Aerosol 150ml", "category_slug": "desodorantes", "brand": "Rexona", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Dove Original Aerosol 150ml", "category_slug": "desodorantes", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Dove Invisible Dry Aerosol 150ml", "category_slug": "desodorantes", "brand": "Dove", "price_reference": 5800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Dove Men+Care Clean Comfort 150ml", "category_slug": "desodorantes", "brand": "Dove", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Axe Dark Temptation Aerosol 150ml", "category_slug": "desodorantes", "brand": "Axe", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Axe Apollo Aerosol 150ml", "category_slug": "desodorantes", "brand": "Axe", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Axe Black Aerosol 150ml", "category_slug": "desodorantes", "brand": "Axe", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Nivea Men Invisible Black & White Aerosol 150ml", "category_slug": "desodorantes", "brand": "Nivea", "price_reference": 5200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Nivea Dry Comfort Aerosol 150ml", "category_slug": "desodorantes", "brand": "Nivea", "price_reference": 5200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Impulse Fantasy Aerosol 107ml", "category_slug": "desodorantes", "brand": "Impulse", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Antitranspirante Gillette Endurance Cool Wave Gel 82g", "category_slug": "desodorantes", "brand": "Gillette", "price_reference": 6500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Desodorante Old Spice Wolfthorn Aerosol 150ml", "category_slug": "desodorantes", "brand": "Old Spice", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Jabón en Barra Dove Original 90g", "category_slug": "jabones", "brand": "Dove", "price_reference": 1800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Dove Exfoliación Suave 90g", "category_slug": "jabones", "brand": "Dove", "price_reference": 1800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Lux Rosas Francesas 125g", "category_slug": "jabones", "brand": "Lux", "price_reference": 1500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Lux Lirio Azul 125g", "category_slug": "jabones", "brand": "Lux", "price_reference": 1500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Nivea Creme Care 90g", "category_slug": "jabones", "brand": "Nivea", "price_reference": 1600, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón Líquido Dove Original Repuesto 220ml", "category_slug": "jabones", "brand": "Dove", "price_reference": 3200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón Líquido Rexona Antibacterial 250ml", "category_slug": "jabones", "brand": "Rexona", "price_reference": 2800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Gel de Ducha Dove Nutrición Intensa 250ml", "category_slug": "jabones", "brand": "Dove", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Gel de Ducha Axe Dark Temptation 250ml", "category_slug": "jabones", "brand": "Axe", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Palmolive Naturals Humectación Refrescante 125g", "category_slug": "jabones", "brand": "Palmolive", "price_reference": 1200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón Líquido Palmolive Naturals 250ml", "category_slug": "jabones", "brand": "Palmolive", "price_reference": 2500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Jabón en Barra Natura Ekos Castanha 100g", "category_slug": "jabones", "brand": "Natura", "price_reference": 2200, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Agua Micelar Garnier Skin Active 400ml", "category_slug": "limpieza-facial", "brand": "Garnier", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Agua Micelar Nivea MicellAir 400ml", "category_slug": "limpieza-facial", "brand": "Nivea", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Agua Micelar L''Oréal Dermo Expertise 400ml", "category_slug": "limpieza-facial", "brand": "L''Oréal", "price_reference": 8500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Gel Limpiador Neutrogena Purified Skin 150g", "category_slug": "limpieza-facial", "brand": "Neutrogena", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Limpiador Facial La Roche-Posay Effaclar Gel 200ml", "category_slug": "limpieza-facial", "brand": "La Roche-Posay", "price_reference": 18000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tónico Facial Nivea Naturally Good 200ml", "category_slug": "limpieza-facial", "brand": "Nivea", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Toallitas Desmaquillantes Nivea x25", "category_slug": "limpieza-facial", "brand": "Nivea", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Limpiador Facial Eucerin DermatoCLEAN Gel 200ml", "category_slug": "limpieza-facial", "brand": "Eucerin", "price_reference": 16000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Espuma Limpiadora Avon Renew 150ml", "category_slug": "limpieza-facial", "brand": "Avon", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Exfoliante Facial Neutrogena Deep Clean 100g", "category_slug": "limpieza-facial", "brand": "Neutrogena", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Crema Hidratante Nivea Creme Facial 100ml", "category_slug": "hidratantes-faciales", "brand": "Nivea", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Anti-Arrugas Nivea Q10 Día 50ml", "category_slug": "hidratantes-faciales", "brand": "Nivea", "price_reference": 9000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Anti-Arrugas Nivea Q10 Noche 50ml", "category_slug": "hidratantes-faciales", "brand": "Nivea", "price_reference": 9500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Sérum Garnier Vitamina C 30ml", "category_slug": "hidratantes-faciales", "brand": "Garnier", "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Hidratante Garnier Skin Active Hyalurónico 50ml", "category_slug": "hidratantes-faciales", "brand": "Garnier", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Facial L''Oréal Revitalift Ácido Hialurónico 50ml", "category_slug": "hidratantes-faciales", "brand": "L''Oréal", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Facial L''Oréal Revitalift Anti-Wrinkle Noche 50ml", "category_slug": "hidratantes-faciales", "brand": "L''Oréal", "price_reference": 13000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Hidratante Eucerin Hyaluron-Filler Día FPS30 50ml", "category_slug": "hidratantes-faciales", "brand": "Eucerin", "price_reference": 28000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Sérum Eucerin Hyaluron-Filler Vitamina C 8ml", "category_slug": "hidratantes-faciales", "brand": "Eucerin", "price_reference": 22000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Hidratante Neutrogena Hydro Boost Water Gel 50g", "category_slug": "hidratantes-faciales", "brand": "Neutrogena", "price_reference": 15000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Sérum La Roche-Posay Hyalu B5 30ml", "category_slug": "hidratantes-faciales", "brand": "La Roche-Posay", "price_reference": 32000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Avon Renew Anti-Edad Día FPS25 50g", "category_slug": "hidratantes-faciales", "brand": "Avon", "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Protector Solar Facial Eucerin Oil Control FPS50 50ml", "category_slug": "hidratantes-faciales", "brand": "Eucerin", "price_reference": 25000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Protector Solar Facial Neutrogena Sun Fresh FPS50 40g", "category_slug": "hidratantes-faciales", "brand": "Neutrogena", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Facial Pond''s Clarant B3 Antimanchas 200g", "category_slug": "hidratantes-faciales", "brand": "Pond''s", "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Facial Pond''s Rejuveness Anti-Arrugas 200g", "category_slug": "hidratantes-faciales", "brand": "Pond''s", "price_reference": 7500, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Set de Brochas Maquillaje x5 piezas", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Brocha Kabuki para Polvo", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pincel para Labios Retráctil", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Esponja de Maquillaje tipo Beauty Blender", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Set de Brochas Maquillaje x12 piezas con Estuche", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Brocha Abanico para Iluminador", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pincel para Delineado Fino", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 1800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Aplicador de Sombras Doble Punta x10", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 1200, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pinza Depilar Acero Inoxidable Punta Oblicua", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Rizador de Pestañas Metálico", "category_slug": "brochas-pinceles", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Espejo de Maquillaje con Aumento x5 Doble Faz", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Espejo de Maquillaje con Luz LED", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Organizador de Maquillaje Acrílico 3 Niveles", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 8000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Organizador Giratorio de Maquillaje Acrílico", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 10000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Neceser de Viaje Grande con Divisiones", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 7000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Porta Brochas Cilíndrico de Cuero Sintético", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Espejo de Bolsillo Compacto Doble", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Caja Organizadora de Esmaltes 48 espacios", "category_slug": "espejos-organizadores", "brand": null, "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Pasta Dental Colgate Total 12 Clean Mint 90g", "category_slug": "jabones", "brand": "Colgate", "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Cepillo Dental Colgate 360 Luminous White", "category_slug": "jabones", "brand": "Colgate", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Enjuague Bucal Listerine Cool Mint 500ml", "category_slug": "jabones", "brand": "Listerine", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Máquina de Afeitar Gillette Mach3 + 2 Cartuchos", "category_slug": "cuidado-corporal", "brand": "Gillette", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Cartuchos Gillette Mach3 x4", "category_slug": "cuidado-corporal", "brand": "Gillette", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Máquina de Afeitar Gillette Prestobarba3 x4", "category_slug": "cuidado-corporal", "brand": "Gillette", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Espuma de Afeitar Gillette Foamy Regular 175g", "category_slug": "cuidado-corporal", "brand": "Gillette", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "After Shave Nivea Men Sensitive 100ml", "category_slug": "cuidado-corporal", "brand": "Nivea", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Crema Depilatoria Veet Piel Sensible 100ml", "category_slug": "cuidado-corporal", "brand": "Veet", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Bandas Depilatorias Veet Easy Gel Wax x20", "category_slug": "cuidado-corporal", "brand": "Veet", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Talco Desodorante Rexona Efficient 200g", "category_slug": "cuidado-corporal", "brand": "Rexona", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Algodón Hidrófilo 200g", "category_slug": "cuidado-corporal", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Hisopos de Algodón x100 unidades", "category_slug": "cuidado-corporal", "brand": null, "price_reference": 1500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Esmalte de Uñas Revlon ColorStay Gel Envy 11.7ml", "category_slug": "cuidado-corporal", "brand": "Revlon", "price_reference": 6000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Quitaesmalte sin Acetona 120ml", "category_slug": "cuidado-corporal", "brand": null, "price_reference": 2000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Lima de Uñas Profesional 180/240", "category_slug": "cuidado-corporal", "brand": null, "price_reference": 800, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Cortaúñas Acero Inoxidable Grande", "category_slug": "cuidado-corporal", "brand": null, "price_reference": 2500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Repelente Off! Family Aerosol 170ml", "category_slug": "cuidado-corporal", "brand": "Off!", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Repelente Off! Active Aerosol 170ml", "category_slug": "cuidado-corporal", "brand": "Off!", "price_reference": 5500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Gel Fijador Pelo Gatsby 220g", "category_slug": "cuidado-corporal", "brand": "Gatsby", "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Cera Modeladora Gatsby 75g", "category_slug": "cuidado-corporal", "brand": "Gatsby", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Pañales Pampers Premium Care RN x36", "category_slug": "jabones", "brand": "Pampers", "price_reference": 14000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañales Pampers Premium Care M x72", "category_slug": "jabones", "brand": "Pampers", "price_reference": 28000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañales Pampers SuperSec G x60", "category_slug": "jabones", "brand": "Pampers", "price_reference": 18000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañales Huggies Supreme Comfort M x68", "category_slug": "jabones", "brand": "Huggies", "price_reference": 26000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañales Huggies Supreme Comfort G x56", "category_slug": "jabones", "brand": "Huggies", "price_reference": 24000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañales Babysec Ultra XG x36", "category_slug": "jabones", "brand": "Babysec", "price_reference": 12000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Toallitas Húmedas Huggies x80", "category_slug": "jabones", "brand": "Huggies", "price_reference": 5000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Toallitas Húmedas Pampers x48", "category_slug": "jabones", "brand": "Pampers", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Toallitas Femeninas Always Noches x8", "category_slug": "cuidado-corporal", "brand": "Always", "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Toallitas Femeninas Always Ultrafina x16", "category_slug": "cuidado-corporal", "brand": "Always", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Protectores Diarios Carefree Original x40", "category_slug": "cuidado-corporal", "brand": "Carefree", "price_reference": 3000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Tampones OB Regular x20", "category_slug": "cuidado-corporal", "brand": "OB", "price_reference": 4500, "unit": "unidad", "sku_prefix": "PERF"},

  {"name": "Papel Higiénico Elite Ultra Doble Hoja x4", "category_slug": "jabones", "brand": "Elite", "price_reference": 4000, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Papel Higiénico Higienol Max x4", "category_slug": "jabones", "brand": "Higienol", "price_reference": 3500, "unit": "unidad", "sku_prefix": "PERF"},
  {"name": "Pañuelos Descartables Elite x10 paquetes", "category_slug": "jabones", "brand": "Elite", "price_reference": 3000, "unit": "unidad", "sku_prefix": "PERF"}
]'::jsonb,
updated_at = CURRENT_TIMESTAMP
WHERE business_type_id = (SELECT id FROM business_types WHERE code = 'perfumeria') AND is_default = true;
