-- =============================================================================
-- SEED 038: Logos de marcas para perfumería
-- Actualiza business_type_templates.brands con logo_url via apistemic.com
-- 53 marcas reales del mercado argentino
-- =============================================================================

UPDATE business_type_templates
SET brands = '[
    {"name": "Natura", "logo_url": "https://logos-api.apistemic.com/domain:natura.com.ar", "suggested_for_categories": ["perfumes-mujer", "perfumes-hombre", "perfumes-unisex", "cremas-corporales", "jabones"]},
    {"name": "Avon", "logo_url": "https://logos-api.apistemic.com/domain:avon.com.ar", "suggested_for_categories": ["perfumes-mujer", "perfumes-unisex", "labiales", "cremas-corporales", "limpieza-facial"]},
    {"name": "L''Oréal", "logo_url": "https://logos-api.apistemic.com/domain:loreal-paris.com.ar", "suggested_for_categories": ["base-correctores", "labiales", "ojos", "shampoo", "acondicionador", "tratamiento-capilar", "hidratantes-faciales", "limpieza-facial"]},
    {"name": "Nivea", "logo_url": "https://logos-api.apistemic.com/domain:nivea.com.ar", "suggested_for_categories": ["cremas-corporales", "desodorantes", "jabones", "limpieza-facial", "hidratantes-faciales"]},
    {"name": "Dove", "logo_url": "https://logos-api.apistemic.com/domain:dove.com", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar", "cremas-corporales", "desodorantes", "jabones"]},
    {"name": "Maybelline", "logo_url": "https://logos-api.apistemic.com/domain:maybelline.com.ar", "suggested_for_categories": ["base-correctores", "labiales", "ojos"]},
    {"name": "Revlon", "logo_url": "https://logos-api.apistemic.com/domain:revlon.com", "suggested_for_categories": ["base-correctores", "labiales", "ojos", "cuidado-corporal"]},
    {"name": "TRESemmé", "logo_url": "https://logos-api.apistemic.com/domain:tresemme.com", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar"]},
    {"name": "Sedal", "logo_url": "https://logos-api.apistemic.com/domain:sedal.com.ar", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar"]},
    {"name": "Pantene", "logo_url": "https://logos-api.apistemic.com/domain:pantene.com", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar"]},
    {"name": "Rexona", "logo_url": "https://logos-api.apistemic.com/domain:rexona.com", "suggested_for_categories": ["desodorantes", "jabones", "cuidado-corporal"]},
    {"name": "Axe", "logo_url": "https://logos-api.apistemic.com/domain:axe.com", "suggested_for_categories": ["desodorantes", "jabones"]},
    {"name": "Gillette", "logo_url": "https://logos-api.apistemic.com/domain:gillette.com", "suggested_for_categories": ["desodorantes", "cuidado-corporal"]},
    {"name": "Garnier", "logo_url": "https://logos-api.apistemic.com/domain:garnier.com.ar", "suggested_for_categories": ["shampoo", "acondicionador", "limpieza-facial", "hidratantes-faciales"]},
    {"name": "Schwarzkopf", "logo_url": "https://logos-api.apistemic.com/domain:schwarzkopf.com", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar"]},
    {"name": "Head & Shoulders", "logo_url": "https://logos-api.apistemic.com/domain:headandshoulders.com", "suggested_for_categories": ["shampoo", "acondicionador"]},
    {"name": "Eucerin", "logo_url": "https://logos-api.apistemic.com/domain:eucerin.com.ar", "suggested_for_categories": ["limpieza-facial", "hidratantes-faciales"]},
    {"name": "Neutrogena", "logo_url": "https://logos-api.apistemic.com/domain:neutrogena.com", "suggested_for_categories": ["limpieza-facial", "hidratantes-faciales"]},
    {"name": "La Roche-Posay", "logo_url": "https://logos-api.apistemic.com/domain:laroche-posay.com.ar", "suggested_for_categories": ["limpieza-facial", "hidratantes-faciales", "cremas-corporales"]},
    {"name": "Antonio Banderas", "logo_url": "https://logos-api.apistemic.com/domain:antoniobanderas.com", "suggested_for_categories": ["perfumes-hombre"]},
    {"name": "Benetton", "logo_url": "https://logos-api.apistemic.com/domain:benetton.com", "suggested_for_categories": ["perfumes-mujer", "perfumes-hombre", "perfumes-unisex"]},
    {"name": "Palmolive", "logo_url": "https://logos-api.apistemic.com/domain:palmolive.com", "suggested_for_categories": ["jabones"]},
    {"name": "Lux", "logo_url": "https://logos-api.apistemic.com/domain:lux.com", "suggested_for_categories": ["jabones"]},
    {"name": "Colgate", "logo_url": "https://logos-api.apistemic.com/domain:colgate.com", "suggested_for_categories": ["jabones"]},
    {"name": "Hinds", "logo_url": "https://logos-api.apistemic.com/domain:hinds.com.ar", "suggested_for_categories": ["cremas-corporales"]},
    {"name": "Old Spice", "logo_url": "https://logos-api.apistemic.com/domain:oldspice.com", "suggested_for_categories": ["desodorantes"]},
    {"name": "Veet", "logo_url": "https://logos-api.apistemic.com/domain:veet.com", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "Pampers", "logo_url": "https://logos-api.apistemic.com/domain:pampers.com", "suggested_for_categories": ["jabones"]},
    {"name": "Huggies", "logo_url": "https://logos-api.apistemic.com/domain:huggies.com", "suggested_for_categories": ["jabones"]},
    {"name": "Always", "logo_url": "https://logos-api.apistemic.com/domain:always.com", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "Off!", "logo_url": "https://logos-api.apistemic.com/domain:off.com", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "Pond''s", "logo_url": "https://logos-api.apistemic.com/domain:ponds.com", "suggested_for_categories": ["hidratantes-faciales"]},
    {"name": "Listerine", "logo_url": "https://logos-api.apistemic.com/domain:listerine.com", "suggested_for_categories": ["jabones"]},
    {"name": "Kevingston", "logo_url": "https://logos-api.apistemic.com/domain:kevingston.com", "suggested_for_categories": ["perfumes-mujer", "perfumes-hombre"]},
    {"name": "Prüne", "logo_url": "https://logos-api.apistemic.com/domain:prune.com.ar", "suggested_for_categories": ["perfumes-mujer"]},
    {"name": "Paula Cahen D''Anvers", "logo_url": "https://logos-api.apistemic.com/domain:paulacahendanvers.com.ar", "suggested_for_categories": ["perfumes-mujer"]},
    {"name": "Ciel", "logo_url": "https://logos-api.apistemic.com/domain:ciel.com.ar", "suggested_for_categories": ["perfumes-mujer"]},
    {"name": "Kevin", "logo_url": "https://logos-api.apistemic.com/domain:kevinperfumes.com.ar", "suggested_for_categories": ["perfumes-hombre"]},
    {"name": "Colbert", "logo_url": "https://logos-api.apistemic.com/domain:colbert.com.ar", "suggested_for_categories": ["perfumes-hombre"]},
    {"name": "Patrichs", "logo_url": "https://logos-api.apistemic.com/domain:patrichs.com.ar", "suggested_for_categories": ["perfumes-hombre"]},
    {"name": "Bross London", "logo_url": "https://logos-api.apistemic.com/domain:brosslondon.com", "suggested_for_categories": ["perfumes-hombre"]},
    {"name": "Etiquet", "logo_url": "https://logos-api.apistemic.com/domain:etiquet.com.ar", "suggested_for_categories": ["perfumes-unisex"]},
    {"name": "Impulse", "logo_url": "https://logos-api.apistemic.com/domain:impulse.com", "suggested_for_categories": ["desodorantes"]},
    {"name": "Plusbelle", "logo_url": "https://logos-api.apistemic.com/domain:plusbelle.com.ar", "suggested_for_categories": ["shampoo", "acondicionador", "tratamiento-capilar"]},
    {"name": "Suave", "logo_url": "https://logos-api.apistemic.com/domain:suave.com", "suggested_for_categories": ["shampoo", "acondicionador"]},
    {"name": "Issue", "logo_url": "https://logos-api.apistemic.com/domain:issueprofessional.com", "suggested_for_categories": ["tratamiento-capilar"]},
    {"name": "Vasenol", "logo_url": "https://logos-api.apistemic.com/domain:vasenol.com", "suggested_for_categories": ["cremas-corporales"]},
    {"name": "Babysec", "logo_url": "https://logos-api.apistemic.com/domain:babysec.com", "suggested_for_categories": ["jabones"]},
    {"name": "Carefree", "logo_url": "https://logos-api.apistemic.com/domain:carefree.com", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "OB", "logo_url": "https://logos-api.apistemic.com/domain:ob-tampons.com", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "Gatsby", "logo_url": "https://logos-api.apistemic.com/domain:gatsby.com.ar", "suggested_for_categories": ["cuidado-corporal"]},
    {"name": "Elite", "logo_url": "https://logos-api.apistemic.com/domain:elite.cl", "suggested_for_categories": ["jabones"]},
    {"name": "Higienol", "logo_url": "https://logos-api.apistemic.com/domain:higienol.com.ar", "suggested_for_categories": ["jabones"]}
  ]'::jsonb,
updated_at = CURRENT_TIMESTAMP
WHERE business_type_id = (SELECT id FROM business_types WHERE code = 'perfumeria') AND is_default = true;
